sudo: false
language: emacs-lisp
cache:
  - directories:
      - $HOME/emacs/
env:
  global:
    - PATH=$HOME/local/bin:$HOME/local/evm/bin:$PATH
jobs:
  include:
    - os: linux
      dist: trusty
      env: EVM_EMACS=emacs-26.1-travis
    - os: linux
      dist: trusty
      env: EVM_EMACS=emacs-26.2-travis
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-26.3-travis-linux-xenial
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-27.1-travis-linux-xenial
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-git-snapshot-travis-linux-xenial
before_script:
  - sh .travis-ci/install-evm.sh $EVM_EMACS
script:
  - emacs --version
  - make EMACS="emacs --debug-init"
  - make clean
  - make distclean
